import { useRef, useState, type FormEvent } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowUpFromLine, CalendarDays, FileText, MapPin, Package, Plus, Repeat2, Save, Trash2, Truck, Users } from 'lucide-react';
import type { TransportPlan } from '../transport/types';
import type { LogisticsOfficeState, LogisticsOrder, LogisticsOrderInput, LogisticsPlace } from './types';
import { Field } from './Ui';

const emptyPlace = (): LogisticsPlace => ({ name: '', address: '', postalCode: '', city: '' });
const minute = (value: string) => { const [hour, minutes] = value.split(':').map(Number); return hour * 60 + minutes; };
const clock = (value?: number) => value === undefined ? '08:00' : `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`;
export type WorkOrderPrefill = Partial<LogisticsOrderInput> & { articleId?: string; articleName?: string; estimatedKg?: number; address?: string };

export default function WorkOrderForm({ state, selectedSite = 'all', prefill, order, canPlan = false, onClose, onSave, onBusyChange }: {
  state: LogisticsOfficeState; selectedSite?: string; prefill?: WorkOrderPrefill; order?: LogisticsOrder; canPlan?: boolean;
  onClose: () => void; onSave: (input: LogisticsOrderInput, plan?: TransportPlan, expectedVersion?: number) => Promise<void>;
  onBusyChange?: (busy: boolean) => void;
}) {
  const expectedVersion = useRef(order?.detail.version);
  const initialSite = state.sites.find(site => site.id === (order?.detail.siteId ?? prefill?.siteId ?? selectedSite)) ?? state.sites[0];
  const sitePlace = (siteId: string): LogisticsPlace => { const site = state.sites.find(value => value.id === siteId); return site ? { name: `JEROC · ${site.name}`, address: site.address, postalCode: site.postalCode, city: site.city } : emptyPlace(); };
  const initialCustomer = state.customers.find(customer => customer.id === prefill?.customerId), initialVessel = state.vessels.find(vessel => vessel.id === prefill?.vesselId);
  const initialCustomerPlace = initialVessel?.place ?? (initialCustomer ? { name: initialCustomer.name, address: prefill?.address ?? initialCustomer.address, postalCode: initialCustomer.postalCode, city: initialCustomer.city, number: initialCustomer.number, contact: initialCustomer.contactPerson, phone: initialCustomer.phone } : emptyPlace());
  const [input, setInput] = useState<LogisticsOrderInput>(() => order ? {
    siteId: order.detail.siteId, action: order.action, customerId: order.customerId, from: order.detail.from, to: order.detail.to,
    operator: order.detail.operator, carrierId: order.detail.carrierId, vesselId: order.detail.vesselId, replacementVesselId: order.detail.replacementVesselId,
    agreementId: order.detail.agreementId, vesselType: order.vesselType, vesselSize: order.vesselSize,
    materialRows: order.detail.materialRows.map(row => ({ articleId: row.articleId, plannedKg: row.plannedKg })), requestedWindow: order.detail.requestedWindow,
    priority: order.detail.priority, durationMinutes: order.durationMinutes, handling: order.detail.handling, notes: order.notes, lat: order.lat, lng: order.lng,
  } : {
    siteId: initialSite?.id ?? '', action: prefill?.action ?? 'pickup', from: prefill?.action === 'outbound' || prefill?.action === 'placement' ? sitePlace(initialSite?.id ?? '') : initialCustomerPlace,
    to: prefill?.action === 'outbound' || prefill?.action === 'placement' ? initialCustomerPlace : sitePlace(initialSite?.id ?? ''), operator: 'own',
    vesselType: 'container', materialRows: prefill?.articleId ? [{ articleId: prefill.articleId, plannedKg: prefill.estimatedKg ?? 0 }] : [], durationMinutes: 60, priority: 'normal', handling: '', notes: '',
    ...prefill,
  });
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [driverId, setDriverId] = useState(order?.detail.assignedDriverId ?? order?.driverId ?? ''), [vehicleId, setVehicleId] = useState(order?.detail.assignedVehicleId ?? order?.vehicleId ?? '');
  const [bookExact, setBookExact] = useState(Boolean(order?.date && order?.startMinute !== undefined));
  const [bookDate, setBookDate] = useState(order?.date ?? ''), [bookTime, setBookTime] = useState(clock(order?.startMinute));
  const patch = (next: Partial<LogisticsOrderInput>) => { setInput(old => ({ ...old, ...next })); setError(''); };
  const outward = input.action === 'outbound' || input.action === 'placement';
  const external = input.operator === 'external';
  const customerPlace = (customerId?: string) => { const customer = state.customers.find(value => value.id === customerId); return customer ? { name: customer.name, address: customer.address, postalCode: customer.postalCode, city: customer.city, number: customer.number, contact: customer.contactPerson, phone: customer.phone } : emptyPlace(); };
  function chooseCustomer(customerId: string) { patch({ customerId: customerId || undefined, ...(outward ? { to: customerPlace(customerId) } : { from: customerPlace(customerId) }) }); }
  function chooseSite(siteId: string) { patch({ siteId, vesselId: undefined, replacementVesselId: undefined, ...(outward ? { from: sitePlace(siteId) } : { to: sitePlace(siteId) }) }); }
  function chooseAction(action: LogisticsOrderInput['action']) {
    const nextOutward = action === 'outbound' || action === 'placement';
    patch({ action, ...(nextOutward !== outward ? { from: nextOutward ? sitePlace(input.siteId) : customerPlace(input.customerId), to: nextOutward ? customerPlace(input.customerId) : sitePlace(input.siteId) } : {}) });
  }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return;
    setBusy(true); onBusyChange?.(true); setError('');
    try {
      if (external && !input.carrierId) throw new Error('Välj ett åkeri för den externa transporten.');
      if (input.requestedWindow && !input.requestedWindow.date && input.priority !== 'asap') throw new Error('Välj ett datum för det önskade tidsfönstret.');
      if (input.materialRows.some(row => !row.articleId || row.plannedKg < 0 || input.action === 'outbound' && row.plannedKg <= 0)) throw new Error(input.action === 'outbound' ? 'Välj artikel och en planerad mängd över 0 kg för varje rad.' : 'Välj artikel och ange uppskattad mängd. 0 kg betyder att vikten inte är känd än.');
      if (canPlan && bookExact && (!driverId || !vehicleId || !bookDate || !bookTime)) throw new Error('Välj förare, fordon, datum och tid för en exakt bokning.');
      const { articleId: _articleId, articleName: _articleName, estimatedKg: _estimatedKg, address: _address, ...clean } = input as LogisticsOrderInput & WorkOrderPrefill;
      await onSave({ ...clean, requestedWindow: input.priority === 'asap' ? undefined : input.requestedWindow, assignedDriverId: external ? undefined : driverId || undefined, assignedVehicleId: external ? undefined : vehicleId || undefined }, !external && canPlan && bookExact ? { date: bookDate, startMinute: minute(bookTime), durationMinutes: input.durationMinutes ?? 60, driverId, vehicleId } : undefined, expectedVersion.current);
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Arbetsordern kunde inte sparas.'); }
    finally { setBusy(false); onBusyChange?.(false); }
  }
  const vessels = state.vessels.filter(value => value.active && value.siteId === input.siteId);
  const actionChoices = [ ['pickup', 'Hämtning', ArrowDownToLine], ['exchange', 'Byte', Repeat2], ['placement', 'Utställning', ArrowUpFromLine], ['outbound', 'Utleverans', Truck] ] as const;
  return <div className="wo-order-form-page">
    <button type="button" className="office-link wo-form-back" disabled={busy} onClick={onClose}><ArrowLeft size={15} />{order ? 'Till arbetsordern' : 'Tillbaka'}</button>
    <header className="wo-title"><div><span className="wo-eyebrow">ARBETSBESTÄLLNING · {initialSite?.name ?? 'JEROC'}</span><h1>{order ? `Redigera ${order.id}` : 'Ny arbetsorder'}</h1><p>Samma arbetsorder följer beställning, planering och utförande.</p></div></header>
    <form onSubmit={submit} className="wo-order-form"><fieldset disabled={busy} className="wo-form-fieldset wo-order-form-layout">
      <section className="office-panel wo-form-section wo-form-type"><h3><Truck size={17} />Typ av arbetsorder</h3><div className="wo-form-type-grid" role="group" aria-label="Typ av arbetsorder">{actionChoices.map(([value, label, Icon]) => <button type="button" key={value} className={input.action === value ? 'active' : ''} aria-pressed={input.action === value} onClick={() => chooseAction(value)}><Icon size={16} />{label}</button>)}</div></section>
      <section className="office-panel wo-form-section wo-form-place"><h3><MapPin size={17} />Plats & kund</h3><div className="wo-form-grid">
        <Field label="Anläggning *"><select required aria-label="Anläggning för arbetsorder" value={input.siteId} onChange={event => chooseSite(event.target.value)}><option value="">Välj anläggning</option>{state.sites.map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></Field>
        <Field label={outward ? 'Mottagare / kund' : 'Kund'}><select aria-label="Kund för arbetsorder" value={input.customerId ?? ''} onChange={event => chooseCustomer(event.target.value)}><option value="">Annan part / välj kund</option>{state.customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></Field>
      </div><PlaceFields label={outward ? 'Leveransplats' : 'Hämtningsplats'} value={outward ? input.to : input.from} onChange={value => patch(outward ? { to: value } : { from: value })} /></section>
      <section className="office-panel wo-form-section wo-form-operator"><h3><Users size={17} />Vem ska köra?</h3><div className="wo-operator-toggle"><button type="button" className={!external ? 'active' : ''} aria-pressed={!external} onClick={() => patch({ operator: 'own', carrierId: undefined })}><Users size={16} />Egna chaufförer</button><button type="button" className={external ? 'active' : ''} aria-pressed={external} onClick={() => { patch({ operator: 'external' }); setBookExact(false); }}><Truck size={16} />Extern transportör</button></div>
        {external ? <Field label="Åkeri *"><select required aria-label="Åkeri för arbetsorder" value={input.carrierId ?? ''} onChange={event => patch({ carrierId: event.target.value || undefined })}><option value="">Välj åkeri</option>{state.carriers.map(carrier => <option key={carrier.id} value={carrier.id}>{carrier.name}</option>)}</select><small className="wo-form-hint">Förfrågan skickas från arbetsordern efter att du sparat. Åkeriet väljer chaufför senare.</small></Field> : <><div className="wo-form-grid"><Field label="Förare (valfri)"><select aria-label="Förare för arbetsorder" value={driverId} onChange={event => { setDriverId(event.target.value); const driver = state.drivers.find(value => value.id === event.target.value); if (driver) setVehicleId(driver.vehicleId); }}><option value="">Ej tilldelad</option>{state.drivers.filter(driver => !driver.companyId).map(driver => <option key={driver.id} value={driver.id}>{driver.name}</option>)}</select></Field><Field label="Fordon (valfritt)"><select aria-label="Fordon för arbetsorder" value={vehicleId} onChange={event => setVehicleId(event.target.value)}><option value="">Ej tilldelat</option>{state.vehicles.map(vehicle => <option key={vehicle.id} value={vehicle.id}>{vehicle.name} · {vehicle.registration}</option>)}</select></Field></div><small className="wo-form-hint">Obokade arbetsordrar går att bemanna och planera senare.</small></>}
      </section>
      <section className="office-panel wo-form-section wo-form-time"><h3><CalendarDays size={17} />Tid & planering</h3><div className="wo-form-grid"><Field label="Prioritet"><select value={input.priority ?? 'normal'} onChange={event => patch({ priority: event.target.value as 'normal' | 'asap' })}><option value="normal">Önskad dag / tidsfönster</option><option value="asap">Så snart som möjligt</option></select></Field><Field label="Uppskattad tidsåtgång (minuter)"><input aria-label="Uppskattad tidsåtgång" type="number" min="15" max="480" step="15" required value={input.durationMinutes ?? 60} onChange={event => patch({ durationMinutes: Number(event.target.value) })} /></Field>
      {input.priority !== 'asap' && <><Field label="Önskat datum"><input type="date" value={input.requestedWindow?.date ?? ''} onChange={event => patch({ requestedWindow: event.target.value ? { ...input.requestedWindow, date: event.target.value } : undefined })} /></Field><div className="wo-form-grid"><Field label="Från (valfritt)"><input type="time" step="900" value={input.requestedWindow?.from ?? ''} onChange={event => patch({ requestedWindow: { date: input.requestedWindow?.date ?? '', from: event.target.value || undefined, to: input.requestedWindow?.to } })} /></Field><Field label="Till (valfritt)"><input type="time" step="900" value={input.requestedWindow?.to ?? ''} onChange={event => patch({ requestedWindow: { date: input.requestedWindow?.date ?? '', from: input.requestedWindow?.from, to: event.target.value || undefined } })} /></Field></div></>}
      </div>{!external && canPlan && <><label className="wo-form-line"><input type="checkbox" checked={bookExact} disabled={Boolean(order?.date)} onChange={event => setBookExact(event.target.checked)} /><CalendarDays size={16} />{order?.date ? 'Uppdatera den exakta bokningen' : 'Boka exakt tid i planeraren'}</label>{bookExact && <div className="wo-form-grid"><Field label="Bokningsdatum *"><input type="date" required value={bookDate} onChange={event => setBookDate(event.target.value)} /></Field><Field label="Starttid *"><input type="time" step="900" required value={bookTime} onChange={event => setBookTime(event.target.value)} /></Field></div>}{order?.date && <small className="wo-form-hint">Avboka en kalenderbokning i transportplaneraren.</small>}</>}
      <small className="wo-form-hint">Önskad tid är skild från en faktisk bokning och eventuell överenskommen tid.</small></section>
      <section className="office-panel wo-form-section wo-form-material"><h3><Package size={17} />Kärl & material</h3><div className="wo-form-grid"><Field label={input.action === 'placement' ? 'Kärl att ställa ut' : 'Kärl att hämta (valfritt)'}><select aria-label="Kärl för arbetsorder" value={input.vesselId ?? ''} onChange={event => { const vessel = vessels.find(value => value.id === event.target.value); patch({ vesselId: event.target.value || undefined, ...(vessel ? { vesselType: vessel.type, vesselSize: vessel.size } : {}) }); }}><option value="">Inget specifikt kärl</option>{vessels.map(vessel => <option key={vessel.id} value={vessel.id}>{vessel.name} · {vessel.size}</option>)}</select></Field><Field label="Kärltyp"><select value={input.vesselType} onChange={event => patch({ vesselType: event.target.value as LogisticsOrderInput['vesselType'] })}><option value="container">Container</option><option value="battery">Batterilåda</option><option value="bin">Tunna / kärl</option><option value="cage">Bur</option></select></Field>{input.action === 'exchange' && <Field label="Ersättningskärl (valfritt)"><select value={input.replacementVesselId ?? ''} onChange={event => patch({ replacementVesselId: event.target.value || undefined })}><option value="">Väljs senare</option>{vessels.filter(vessel => vessel.id !== input.vesselId).map(vessel => <option key={vessel.id} value={vessel.id}>{vessel.name}</option>)}</select></Field>}</div>
      <div style={{ marginTop: 15 }}>{input.materialRows.map((row, index) => <div className="wo-material-row" key={index}><Field label="Artikel"><select aria-label={`Artikel ${index + 1}`} required value={row.articleId} onChange={event => patch({ materialRows: input.materialRows.map((item, at) => at === index ? { ...item, articleId: event.target.value } : item) })}><option value="">Välj artikel</option>{state.articles.map(article => <option key={article.id} value={article.id}>{article.name}{article.hazardous ? ' · farligt avfall' : ''}</option>)}</select></Field><Field label="Planerad mängd (kg)"><input aria-label={`Planerad mängd ${index + 1}`} type="number" min={input.action === 'outbound' ? '0.001' : '0'} step="0.001" required value={input.action === 'outbound' && row.plannedKg === 0 ? '' : row.plannedKg} onChange={event => patch({ materialRows: input.materialRows.map((item, at) => at === index ? { ...item, plannedKg: Number(event.target.value) } : item) })} /></Field><button type="button" className="wo-icon-button" aria-label={`Ta bort artikel ${index + 1}`} onClick={() => patch({ materialRows: input.materialRows.filter((_, at) => at !== index) })}><Trash2 size={16} /></button></div>)}<button type="button" className="office-link" onClick={() => patch({ materialRows: [...input.materialRows, { articleId: '', plannedKg: 0 }] })}><Plus size={15} />Lägg till material</button>{input.action !== 'outbound' && <small className="wo-form-hint">0 kg betyder att mängden inte är känd ännu. Verklig vikt registreras vid lastning.</small>}</div></section>
      <section className="office-panel wo-form-section wo-form-instructions"><h3><FileText size={17} />Instruktioner</h3><div className="wo-form-grid"><Field label="Hantering & lastning" full><textarea value={input.handling ?? ''} maxLength={2000} onChange={event => patch({ handling: event.target.value })} placeholder="Lastningshjälp, åtkomst och säker hantering…" /></Field><Field label="Övriga instruktioner" full><textarea value={input.notes ?? ''} maxLength={2000} onChange={event => patch({ notes: event.target.value })} /></Field></div></section>
    </fieldset><footer className="wo-form-savebar">{error ? <div role="alert" className="wo-form-save-error">{error}</div> : <span className="wo-form-save-hint">{order ? 'Ändringarna sparas på samma arbetsorder.' : 'Tid och bemanning kan kompletteras senare.'}</span>}<div className="wo-actions"><button type="button" className="office-btn outline" disabled={busy} onClick={onClose}>Avbryt</button><button className="office-btn" disabled={busy}><Save size={16} />{busy ? 'Sparar…' : 'Spara arbetsorder'}</button></div></footer></form>
  </div>;
}

function PlaceFields({ label, value, onChange }: { label: string; value: LogisticsPlace; onChange: (value: LogisticsPlace) => void }) {
  const patch = (fields: Partial<LogisticsPlace>) => onChange({ ...value, ...fields });
  return <div className="wo-form-grid" style={{ marginTop: 14 }}><Field label={`${label} · namn *`}><input required value={value.name} maxLength={200} onChange={event => patch({ name: event.target.value })} /></Field><Field label="Gatuadress *"><input required value={value.address} maxLength={300} onChange={event => patch({ address: event.target.value })} /></Field><Field label="Postnummer"><input value={value.postalCode} maxLength={20} onChange={event => patch({ postalCode: event.target.value })} /></Field><Field label="Ort *"><input required value={value.city} maxLength={100} onChange={event => patch({ city: event.target.value })} /></Field><Field label="Kontakt på plats"><input value={value.contact ?? ''} maxLength={200} onChange={event => patch({ contact: event.target.value })} /></Field><Field label="Telefon"><input type="tel" value={value.phone ?? ''} maxLength={40} onChange={event => patch({ phone: event.target.value })} /></Field></div>;
}
