import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, BadgeCheck, Building2, CalendarDays, ChevronRight, Clock, KeyRound, ListChecks, LockKeyhole, Pencil, Plus, RefreshCw, Search, ShieldCheck, Truck, UserRound, Users } from 'lucide-react';
import { can, type OfficeUser } from '../model';
import { readPersonnel, updatePersonnel } from './client';
import type { Competency, Employment, Person, PersonAccountCreation, PersonnelCommand, PersonnelResponse, Salary } from './types';
import { Alert, Dialog, Fact, Field, Panel, Pill, formatDate, initials, localToday, minuteLabel } from './components/Ui';
import SchedulePanel from './components/SchedulePanel';
import StaffingPanel from './components/StaffingPanel';
import './personal.css';

export interface PersonalWorkspaceProps {
  user: OfficeUser; actualUser: OfficeUser; selectedSiteId?: string; users?: OfficeUser[];
  onNotice: (message: string) => void; onOpenUser?: (id: string) => void;
  renderStaffAccount?: (userId: string) => ReactNode; onAccountsChanged?: () => Promise<void> | void;
}
type Modal = 'person' | 'employment' | 'salary' | 'competency' | 'account' | 'company' | null;
const tabNames = { overview: 'Översikt', employment: 'Anställning', schedule: 'Schema & frånvaro', absence: 'Schema & frånvaro', competencies: 'Kompetenser', account: 'Inloggning & behörigheter' };
const employmentNames = { permanent: 'Tillsvidare', temporary: 'Visstid', probation: 'Provanställning', hourly: 'Timanställning' };
const competencyNames = { license: 'Körkortsbehörighet', ykb: 'YKB', adr: 'ADR', employer: 'Arbetsgivarens körtillstånd', other: 'Övrig kompetens' };
const absenceNames = { sick: 'Sjukfrånvaro', holiday: 'Semester', vab: 'Vård av barn', leave: 'Ledighet', training: 'Utbildning' };
const jobsFor = (response: PersonnelResponse, person: Person) => response.transport.orders.filter(order => order.driverId === person.driverId && person.driverId && order.status !== 'cancelled' && order.status !== 'done').sort((a, b) => (a.date ?? a.requestedDate ?? '').localeCompare(b.date ?? b.requestedDate ?? '') || (a.startMinute ?? 0) - (b.startMinute ?? 0));
const competencyStatus = (competency: Competency, at = localToday()) => !competency.verified ? 'unverified' : competency.validFrom > at ? 'future' : competency.validTo && competency.validTo < at ? 'expired' : competency.validTo && competency.validTo <= new Date(Date.now() + 60 * 86400000).toLocaleDateString('sv-SE', { timeZone: 'Europe/Stockholm' }) ? 'soon' : 'valid';
const toneForCompetency = (competency: Competency) => competencyStatus(competency) === 'expired' ? 'red' : ['soon', 'unverified', 'future'].includes(competencyStatus(competency)) ? 'orange' : 'green';
const labelForCompetency = (competency: Competency) => ({ expired: 'Utgången', unverified: 'Inväntar kontroll', future: 'Gäller senare', soon: 'Förnyas snart', valid: 'Giltig' })[competencyStatus(competency)];
function Metric({ label, value, note, icon }: { label: string; value: ReactNode; note: ReactNode; icon: ReactNode }) { return <div className="hr-metric"><span className="hr-metric-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong><small>{note}</small></div></div>; }

export default function PersonalWorkspace({ user, actualUser, selectedSiteId = 'all', users = [], onNotice, onOpenUser, renderStaffAccount, onAccountsChanged }: PersonalWorkspaceProps) {
  const navigate = useNavigate();
  const location = useLocation();
  const [response, setResponse] = useState<PersonnelResponse>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [modal, setModal] = useState<Modal>(null);
  const [editingPerson, setEditingPerson] = useState<Person>();
  const [editingCompetency, setEditingCompetency] = useState<Competency>();
  const [createLoginOnEdit, setCreateLoginOnEdit] = useState(false);
  const [query, setQuery] = useState('');
  const [kindFilter, setKindFilter] = useState('all');
  const [teamFilter, setTeamFilter] = useState('all');
  const [siteFilter, setSiteFilter] = useState('all');
  const [showInactive, setShowInactive] = useState(false);
  const identity = useRef(`${actualUser.id}:${user.id}`);
  identity.current = `${actualUser.id}:${user.id}`;
  const parts = location.pathname.split('/').filter(Boolean);
  const isTasks = parts[1] === 'tasks';
  const personId = !isTasks ? parts[1] : undefined;
  const tab = (parts[2] in tabNames ? parts[2] : 'overview') as keyof typeof tabNames;
  const refresh = useCallback(async () => { const next = await readPersonnel(actualUser.id, user.id); if (identity.current === `${actualUser.id}:${user.id}`) setResponse(next); return next; }, [actualUser.id, user.id]);
  useEffect(() => {
    let current = true;
    setLoading(true); setError(''); setResponse(undefined); setModal(null);
    void refresh().catch(reason => { if (current) setError(reason instanceof Error ? reason.message : 'Personalregistret kunde inte laddas.'); }).finally(() => { if (current) setLoading(false); });
    const interval = window.setInterval(() => { void refresh().catch(() => {}); }, 20000);
    return () => { current = false; window.clearInterval(interval); };
  }, [refresh]);
  const runCommand = useCallback(async (command: PersonnelCommand) => {
    const next = await updatePersonnel(command, actualUser.id, user.id);
    if (!command.action.endsWith('.preview') && identity.current === `${actualUser.id}:${user.id}`) setResponse(next);
    return next;
  }, [actualUser.id, user.id]);
  const closeModal = useCallback(() => { setModal(null); setEditingCompetency(undefined); }, []);
  const permitted = (permission: string) => response?.capabilities.includes(permission as never) ?? false;
  const data = response?.data;
  const visiblePeople = useMemo(() => (data?.people ?? []).filter(person => selectedSiteId === 'all' || !selectedSiteId || person.siteIds.includes(selectedSiteId)), [data?.people, selectedSiteId]);
  const person = visiblePeople.find(value => value.id === personId);
  const siteName = (id: string) => response?.sites.find(site => site.id === id)?.name ?? id;
  const companyName = (value: Person) => data?.companies.find(company => company.id === value.companyId)?.name ?? (value.kind === 'employee' ? 'JEROC Återvinning AB' : 'Åkeri saknas');
  const managerName = (value: Person) => data?.people.find(manager => manager.id === value.managerId)?.name ?? 'Ej vald';
  const openPerson = (id: string, nextTab = 'overview') => { setModal(null); navigate(`/personnel/${encodeURIComponent(id)}/${nextTab}`); };
  const edit = (value?: Person, createLogin = false) => { setEditingPerson(value); setCreateLoginOnEdit(createLogin); setModal('person'); };
  const today = localToday();
  const currentAbsence = (value: Person) => data?.absences.find(absence => absence.personId === value.id && absence.status === 'registered' && absence.fromDate <= today && absence.toDate >= today);
  const availability = (value: Person) => {
    if (!value.active) return <Pill tone="grey">Inaktiv</Pill>;
    const absence = currentAbsence(value);
    if (absence) return <Pill tone="red">{absence.kind ? absenceNames[absence.kind] : 'Frånvarande'}</Pill>;
    if (value.kind === 'external') return <Pill>Tillgänglighet bekräftas</Pill>;
    const weekday = new Date(`${today}T12:00:00Z`).getUTCDay() || 7;
    const schedule = data?.schedules.find(valueSchedule => valueSchedule.personId === value.id && valueSchedule.weekdays.includes(weekday) && valueSchedule.effectiveFrom <= today && (!valueSchedule.effectiveTo || valueSchedule.effectiveTo >= today));
    return schedule ? <Pill tone="green">{minuteLabel(schedule.startMinute)}–{minuteLabel(schedule.endMinute)}</Pill> : <Pill tone="grey">Inget arbetspass idag</Pill>;
  };
  if (loading) return <div className="hr-loading"><RefreshCw size={22} /> Laddar personal…</div>;
  if (error || !response || !data) return <div className="hr-workspace"><Alert tone="red">{error || 'Personalregistret kunde inte laddas.'}</Alert><button className="office-btn outline" onClick={() => { setLoading(true); void refresh().then(() => setError('')).catch(reason => setError(reason.message)).finally(() => setLoading(false)); }}>Försök igen</button></div>;
  const activeTasks = data.staffingTasks.filter(task => task.status === 'open' && visiblePeople.some(value => value.id === task.personId));
  const competencies = person ? data.competencies.filter(value => value.personId === person.id) : [];
  const jobs = person ? jobsFor(response, person) : [];
  const account = person && data.externalAccounts.find(value => value.personId === person.id);
  const accountUsers = response.users ?? users;
  const linkedUser = person && accountUsers.find(value => value.id === person.userId);
  const canManageAccount = person?.kind === 'external' ? permitted('externalAccounts') : can(user, 'users');
  const listedPeople = visiblePeople.filter(value => (showInactive || value.active) && (kindFilter === 'all' || kindFilter === value.kind) && (teamFilter === 'all' || value.team === teamFilter) && (siteFilter === 'all' || value.siteIds.includes(siteFilter)) && [value.name, value.role, value.team, companyName(value), ...data.competencies.filter(c => c.personId === value.id).flatMap(c => [c.name, c.scope, ...c.codes])].join(' ').toLocaleLowerCase('sv-SE').includes(query.toLocaleLowerCase('sv-SE')));

  return <div className="hr-workspace">
    <nav className="hr-section-nav" aria-label="Personal"><button className={!isTasks ? 'active' : ''} onClick={() => navigate('/personnel')}>Alla personer</button><button className={isTasks ? 'active' : ''} onClick={() => navigate('/personnel/tasks')}>Bemanning att lösa{activeTasks.length > 0 && <span className="hr-count">{activeTasks.length}</span>}</button>{can(user, 'users') && <button onClick={() => navigate('/personnel/accounts')}>Konton</button>}</nav>
    {isTasks ? <StaffingPanel response={{ ...response, data: { ...data, staffingTasks: data.staffingTasks.filter(task => visiblePeople.some(value => value.id === task.personId)) } }} runCommand={runCommand} onOpenPerson={openPerson} onOpenOrder={() => navigate('/transport')} /> : personId && !person ? <Alert tone="orange">Personen finns inte eller hör inte till den valda anläggningen. <button className="office-link" onClick={() => navigate('/personnel')}>Visa personallistan</button></Alert> : person ? <>
      <button className="office-back" onClick={() => navigate('/personnel')}><ArrowLeft size={16} /> Till personal</button>
      <div className="hr-person-header"><div className={`hr-avatar large${person.kind === 'external' ? ' external' : ''}`}>{initials(person.name)}</div><div><h1>{person.name}</h1><div className="hr-person-badges"><Pill tone={person.active ? 'green' : 'grey'}>{person.kind === 'external' ? 'Extern chaufför' : 'Anställd'}</Pill>{person.canDrive && <Pill>Förare</Pill>}</div><p>{person.team || person.role} · {person.siteIds.map(siteName).join(', ')}{person.employeeNumber && ` · ${person.employeeNumber}`}{person.kind === 'external' && ` · ${companyName(person)}`}</p></div><div className="hr-header-actions">{availability(person)}{canManageAccount ? <button className="office-btn outline" onClick={() => openPerson(person.id, 'account')}><UserRound size={16} /> Inloggning<Pill tone={person.kind === 'external' ? account?.active ? 'green' : 'grey' : person.userId && linkedUser?.active !== false ? 'green' : 'grey'}>{person.kind === 'external' ? account ? account.active ? 'Aktivt' : 'Avaktiverat' : 'Ej skapat' : person.userId ? linkedUser?.active === false ? 'Spärrat' : 'Kopplat' : 'Ej skapat'}</Pill></button> : !person.userId && !account && <Pill tone="grey">Ingen inloggning</Pill>}</div></div>
      <nav className="hr-tabs" aria-label="Personalkortets flikar">{Object.entries(tabNames).filter(([id]) => id !== 'absence' && !(person.kind === 'external' && id === 'employment') && (id !== 'account' || canManageAccount)).map(([id, name]) => <button key={id} className={tab === id || id === 'schedule' && tab === 'absence' ? 'active' : ''} onClick={() => openPerson(person.id, id)}>{name}</button>)}</nav>
      {tab === 'overview' && <>
        <div className="hr-metrics three"><Metric label="Kommande uppdrag" value={jobs.length} note={jobs[0]?.date ? formatDate(jobs[0].date) : 'Inga bokade uppdrag'} icon={<Truck size={22} />} /><Metric label="Kompetenser" value={`${competencies.filter(c => ['valid', 'soon'].includes(competencyStatus(c))).length} giltiga`} note={`${competencies.filter(c => competencyStatus(c) === 'expired').length} utgångna`} icon={<BadgeCheck size={22} />} /><Metric label="Bemanning att lösa" value={activeTasks.filter(task => task.personId === person.id).length} note={`Ansvarig: ${managerName(person)}`} icon={<ListChecks size={22} />} /></div>
        <div className="hr-grid two"><Panel title={person.kind === 'external' ? 'Förare & åkeri' : 'Kontakt & organisation'} actions={permitted('personnelWrite') && <button className="office-link" onClick={() => edit(person)}><Pencil size={14} /> Redigera</button>}><Fact label="Telefon">{person.phone || '—'}</Fact><Fact label="E-post">{person.email || '—'}</Fact>{person.kind === 'external' ? <><Fact label="Åkeri">{companyName(person)}</Fact><Fact label="Organisationsnummer">{data.companies.find(company => company.id === person.companyId)?.number || '—'}</Fact><Fact label="Åkeriets kontakt">{data.companies.find(company => company.id === person.companyId)?.contact || '—'}</Fact></> : <Fact label="Chef / gruppledare">{managerName(person)}</Fact>}<Fact label="Team">{person.team || '—'}</Fact><Fact label="Anläggning">{person.siteIds.map(siteName).join(', ')}</Fact><div className="hr-driver-toggle"><div><strong>Kan bokas som förare</strong><small>Kompetens och schema kontrolleras vid bokning.</small></div><input type="checkbox" role="switch" aria-label="Kan bokas som förare" checked={person.canDrive} disabled={!permitted('personnelWrite')} onChange={() => void runCommand({ action: 'person.save', person: { ...person, canDrive: !person.canDrive } }).then(() => onNotice('Förarprofilen är uppdaterad.')).catch(reason => onNotice(reason.message))} /></div>{person.kind === 'external' && <Alert>Extern person, kopplad till åkeriet. Anställning och lön hos åkeriet registreras inte här.</Alert>}</Panel>
        <Panel title="Kommande uppdrag" actions={<button className="office-link" onClick={() => openPerson(person.id, 'schedule')}>Visa schema <ChevronRight size={14} /></button>}><JobTable response={response} person={person} /></Panel>
        <Panel title="Kompetenser att följa upp" actions={<button className="office-link" onClick={() => openPerson(person.id, 'competencies')}>Öppna kompetenser <ChevronRight size={14} /></button>}>{competencies.filter(c => competencyStatus(c) !== 'valid').length ? competencies.filter(c => competencyStatus(c) !== 'valid').map(c => <div className="hr-fact" key={c.id}><span>{c.name}</span><Pill tone={toneForCompetency(c)}>{labelForCompetency(c)}{c.validTo && ` · ${formatDate(c.validTo)}`}</Pill></div>) : <div className="hr-empty"><ShieldCheck size={26} /><strong>Inga kompetensvarningar</strong></div>}</Panel>
        {person.kind === 'external' && <Panel title="Åtkomst till uppdrag" icon={<ShieldCheck size={18} />}><Fact label="Användarnamn">{account?.username || 'Ej skapat'}</Fact><Fact label="Kontostatus"><Pill tone={account?.active ? 'green' : 'grey'}>{account?.active ? 'Aktivt' : account ? 'Avaktiverat' : 'Ej skapat'}</Pill></Fact><Fact label="Åtkomst">Egna tilldelade uppdrag</Fact>{permitted('externalAccounts') && <button className="office-btn outline" onClick={() => openPerson(person.id, 'account')}><KeyRound size={15} /> Hantera konto</button>}<Alert>Åkeriets upphämtningstid är ett önskemål tills planeringen har bekräftats.</Alert></Panel>}</div>
      </>}
      {tab === 'account' && (canManageAccount ? person.kind === 'external' ? <Panel title="Inloggning & behörigheter" icon={<KeyRound size={18} />} actions={<button className="office-btn" onClick={() => !account && (!person.canDrive || !person.vehicleId) ? edit(person, true) : setModal('account')}><Pencil size={15} /> {account ? 'Hantera inloggning' : 'Skapa inloggning'}</button>}><Fact label="Användarnamn">{account?.username || 'Ej skapat'}</Fact><Fact label="Kontostatus"><Pill tone={account?.active ? 'green' : 'grey'}>{account ? account.active ? 'Aktivt' : 'Avaktiverat' : 'Ej skapat'}</Pill></Fact><Fact label="Åkeri">{companyName(person)}</Fact><Fact label="Åtkomst">Egna tilldelade uppdrag</Fact><Fact label="Inloggning"><a className="office-link" href="/chauffor" target="_blank" rel="noopener noreferrer">Öppna chaufförsinloggningen <ChevronRight size={14} /></a></Fact><Alert>Kontot ger åtkomst till personens egna uppdrag. Återställt lösenord eller avaktivering avslutar befintliga inloggningar.</Alert></Panel> : person.userId ? !linkedUser ? <Panel title="Inloggning & behörigheter" icon={<KeyRound size={18} />}><Fact label="Kontostatus"><Pill tone="green">Kopplat konto</Pill></Fact><Alert>Du kan inte administrera det kopplade kontot. Personen och kontots historik finns kvar.</Alert></Panel> : renderStaffAccount ? renderStaffAccount(person.userId) : <Panel title="Inloggning & behörigheter"><Fact label="Konto">{linkedUser?.name || person.userId}</Fact><button className="office-btn" onClick={() => onOpenUser?.(person.userId!)}>Hantera behörigheter</button></Panel> : <Panel title="Inloggning & behörigheter" icon={<KeyRound size={18} />}><div className="hr-empty"><UserRound size={30} /><strong>Personen har inget kopplat konto</strong><p>Skapa ett konto eller koppla en befintlig inloggning till personkortet.</p>{permitted('personnelWrite') && <button className="office-btn" onClick={() => edit(person, true)}><Plus size={16} /> Skapa eller koppla konto</button>}</div></Panel> : <Alert tone="orange">Du saknar behörighet att hantera den här personens konto.</Alert>)}
      {tab === 'employment' && person.kind === 'employee' && <EmploymentView response={response} person={person} onEdit={() => setModal('employment')} onSalaryEdit={() => setModal('salary')} />}
      {(tab === 'schedule' || tab === 'absence') && <SchedulePanel response={response} person={person} activeTab={tab} runCommand={runCommand} onOpenStaffing={() => navigate('/personnel/tasks')} />}
      {tab === 'competencies' && <><div className="hr-metrics three"><Metric label="Giltiga kompetenser" value={competencies.filter(c => ['valid', 'soon'].includes(competencyStatus(c))).length} note="Verifierade och giltiga idag" icon={<BadgeCheck size={22} />} /><Metric label="Förnyas snart" value={competencies.filter(c => competencyStatus(c) === 'soon').length} note="Inom 60 dagar" icon={<Clock size={22} />} /><Metric label="Utgångna / ej verifierade" value={competencies.filter(c => ['expired', 'unverified'].includes(competencyStatus(c))).length} note="Kan inte uppfylla obligatoriska uppdragskrav" icon={<ShieldCheck size={22} />} /></div><Panel title="Kompetenser & fordonsbehörighet" actions={permitted('competenciesWrite') && <button className="office-btn" onClick={() => { setEditingCompetency(undefined); setModal('competency'); }}><Plus size={16} /> Lägg till kompetens</button>}><div className="hr-table-scroll"><table className="office-table hr-table"><thead><tr><th>Kompetens</th><th>Omfattning</th><th>Giltighet</th><th>Verifiering</th><th>Status</th><th></th></tr></thead><tbody>{competencies.map(c => <tr key={c.id}><td><strong>{c.name}</strong><small>{competencyNames[c.type]}</small></td><td>{c.scope || c.codes.join(' / ') || '—'}</td><td>{formatDate(c.validFrom)}<small>Till {formatDate(c.validTo)}</small></td><td>{c.verified ? 'Kontrollerad' : 'Inväntar kontroll'}<small>{c.verifiedBy ? data.people.find(value => value.userId === c.verifiedBy || value.id === c.verifiedBy)?.name ?? c.verifiedBy : ''}</small></td><td><Pill tone={toneForCompetency(c)}>{labelForCompetency(c)}</Pill></td><td>{permitted('competenciesWrite') && <button className="office-link" aria-label={`Redigera ${c.name}`} onClick={() => { setEditingCompetency(c); setModal('competency'); }}><Pencil size={14} /> Ändra</button>}</td></tr>)}</tbody></table>{!competencies.length && <div className="hr-empty">Inga kompetenser registrerade.</div>}</div><Alert>Körkort, YKB, ADR och arbetsgivarens körtillstånd bedöms separat. Farligt avfall innebär inte automatiskt ADR-krav.</Alert></Panel></>}
    </> : <>
      <div className="office-page-title"><div><span className="hr-eyebrow">PERSONAL · GEMENSAMT PERSONREGISTER</span><h1>Personal</h1><p>Anställda och externa chaufförer, med koppling till användarkonto och planering.</p></div>{permitted('personnelWrite') && <button className="office-btn" onClick={() => edit()}><Plus size={17} /> Lägg till person</button>}</div>
      <div className="hr-metrics"><Metric label="Aktiva personer" value={visiblePeople.filter(value => value.active).length} note={`${visiblePeople.filter(value => value.active && value.kind === 'employee').length} anställda · ${visiblePeople.filter(value => value.active && value.kind === 'external').length} externa`} icon={<Users size={22} />} /><Metric label="Bokningsbara förare" value={visiblePeople.filter(value => value.active && value.canDrive).length} note="Personer med förarprofil" icon={<Truck size={22} />} /><Metric label="Frånvarande idag" value={visiblePeople.filter(value => currentAbsence(value)).length} note={formatDate(today)} icon={<CalendarDays size={22} />} /><Metric label="Bemanning att lösa" value={activeTasks.length} note="Uppdrag som behöver ersättare" icon={<ListChecks size={22} />} /></div>
      {activeTasks.length > 0 && <Alert tone="orange"><strong>{activeTasks.length} uppdrag behöver ny bemanning.</strong><span>Bokningarna ligger kvar tills en ansvarig har löst uppgifterna.</span><button className="office-link" onClick={() => navigate('/personnel/tasks')}>Visa bemanning <ChevronRight size={14} /></button></Alert>}
      <section className="office-panel hr-panel"><div className="hr-filters"><label className="hr-search"><Search size={17} /><input aria-label="Sök person" placeholder="Sök namn, befattning, företag eller kompetens…" value={query} onChange={event => setQuery(event.target.value)} /></label><select aria-label="Persontyp" value={kindFilter} onChange={event => setKindFilter(event.target.value)}><option value="all">Alla personer</option><option value="employee">Anställda</option><option value="external">Externa chaufförer</option></select><select aria-label="Team" value={teamFilter} onChange={event => setTeamFilter(event.target.value)}><option value="all">Alla team</option>{Array.from(new Set(visiblePeople.map(value => value.team).filter(Boolean))).sort().map(team => <option key={team}>{team}</option>)}</select><select aria-label="Anläggning i personallistan" value={siteFilter} onChange={event => setSiteFilter(event.target.value)}><option value="all">Alla anläggningar</option>{response.sites.filter(site => selectedSiteId === 'all' || selectedSiteId === site.id).map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></div><label className="hr-checkbox"><input type="checkbox" checked={showInactive} onChange={event => setShowInactive(event.target.checked)} /> Visa även inaktiva personer</label><div className="hr-table-scroll"><table className="office-table hr-table hr-people-table"><thead><tr><th>Person</th><th>Anläggning / team</th><th>Företag</th><th>Tillgänglighet idag</th><th>Kompetens / uppmärksamma</th><th></th></tr></thead><tbody>{listedPeople.map(value => <tr key={value.id}><td><div className="hr-person-chip"><span className={`hr-avatar${value.kind === 'external' ? ' external' : ''}`}>{initials(value.name)}</span><div><button className="hr-name-button" onClick={() => openPerson(value.id)}>{value.name}</button><small>{value.role || (value.canDrive ? 'Chaufför' : 'Medarbetare')} · {value.kind === 'employee' ? 'Anställd' : 'Extern'}</small></div></div></td><td>{value.siteIds.map(siteName).join(', ')}<small>{value.team}</small></td><td>{companyName(value)}</td><td>{availability(value)}</td><td>{activeTasks.some(task => task.personId === value.id) ? <Pill tone="orange">{activeTasks.filter(task => task.personId === value.id).length} uppdrag berörs</Pill> : data.competencies.filter(c => c.personId === value.id && c.verified && competencyStatus(c) !== 'expired').map(c => c.scope || c.codes.join('/')).filter(Boolean).join(' · ') || '—'}</td><td><button className="office-link" onClick={() => openPerson(value.id)}>Öppna <ChevronRight size={14} /></button></td></tr>)}</tbody></table>{!listedPeople.length && <div className="hr-empty"><Users size={27} />Inga personer matchar filtren.</div>}</div><p className="hr-muted hr-list-foot">Visar {listedPeople.length} personer · Sparas gemensamt på servern.</p></section><Alert>En person kan finnas utan inloggning. Förarprofil, anställning och systembehörigheter hanteras separat.</Alert>
    </>}
    {modal === 'person' && <PersonForm response={response} person={editingPerson} users={accountUsers} createLoginOnEdit={createLoginOnEdit} onClose={closeModal} onCompany={() => setModal('company')} onSave={async (value, clearFields, createAccount) => { const next = await runCommand({ action: 'person.save', person: value, clearFields, ...(createAccount ? { createAccount } : {}) }); const saved = next.data.people.find(p => p.id === value.id); if (createAccount || saved?.userId !== editingPerson?.userId) await onAccountsChanged?.(); closeModal(); if (saved) openPerson(saved.id, createAccount || saved.userId !== editingPerson?.userId ? 'account' : 'overview'); onNotice(createAccount ? 'Personen och inloggningen är skapade.' : 'Personen är sparad.'); }} />}
    {modal === 'company' && <CompanyForm onClose={() => setModal('person')} onSave={async company => { await runCommand({ action: 'company.save', company }); setModal('person'); onNotice('Åkeriet är sparat. Välj det i personformuläret.'); }} />}
    {modal === 'employment' && person && <EmploymentForm person={person} value={data.employment.find(value => value.personId === person.id)} onClose={closeModal} onSave={async employment => { await runCommand({ action: 'employment.save', employment }); closeModal(); onNotice('Anställningen är sparad.'); }} />}
    {modal === 'salary' && person && <SalaryForm person={person} value={data.salaries.find(value => value.personId === person.id)} onClose={closeModal} onSave={async salary => { await runCommand({ action: 'salary.save', salary }); closeModal(); onNotice('Löneuppgifterna är sparade.'); }} />}
    {modal === 'competency' && person && <CompetencyForm person={person} value={editingCompetency} onClose={closeModal} onSave={async competency => { await runCommand({ action: 'competency.save', competency }); closeModal(); onNotice('Kompetensen är sparad.'); }} />}
    {modal === 'account' && person && <ExternalAccountForm person={person} response={response} onClose={closeModal} onSave={async command => { await runCommand(command); await onAccountsChanged?.(); onNotice('Det externa kontot är uppdaterat.'); }} />}
  </div>;
}

function JobTable({ response, person }: { response: PersonnelResponse; person: Person }) {
  const jobs = jobsFor(response, person);
  return jobs.length ? <div className="hr-table-scroll"><table className="office-table hr-table"><thead><tr><th>Tid</th><th>Uppdrag</th><th>Status</th></tr></thead><tbody>{jobs.slice(0, 8).map(job => <tr key={job.id}><td>{formatDate(job.date ?? job.requestedDate)}<small>{job.startMinute === undefined ? 'Önskad upphämtning' : `${minuteLabel(job.startMinute)}–${minuteLabel(job.startMinute + job.durationMinutes)}`}</small></td><td><strong>{job.id} · {job.customerName}</strong><small>{job.material} · {job.city}</small></td><td><Pill tone={response.data.staffingTasks.some(task => task.orderId === job.id && task.status === 'open') ? 'orange' : job.status === 'unbooked' ? 'grey' : 'blue'}>{response.data.staffingTasks.some(task => task.orderId === job.id && task.status === 'open') ? 'Behöver förare' : job.status === 'unbooked' ? 'Ej bokat' : job.status === 'on_way' ? 'På väg' : 'Bokat'}</Pill></td></tr>)}</tbody></table></div> : <div className="hr-empty"><Truck size={27} /><strong>Inga kommande uppdrag</strong><p>Uppdrag kopplas till personens förarprofil i transportplaneraren.</p></div>;
}
function EmploymentView({ response, person, onEdit, onSalaryEdit }: { response: PersonnelResponse; person: Person; onEdit: () => void; onSalaryEdit: () => void }) {
  const employment = response.data.employment.find(value => value.personId === person.id);
  const salary = response.data.salaries.find(value => value.personId === person.id);
  const cap = (permission: string) => response.capabilities.includes(permission as never);
  return <div className="hr-grid two"><Panel title="Anställning" icon={<Building2 size={18} />} actions={cap('employmentWrite') && <button className="office-link" onClick={onEdit}><Pencil size={14} /> Redigera</button>}>{cap('employmentRead') ? <><Fact label="Anställningsform">{employment ? employmentNames[employment.form] : 'Ej registrerad'}</Fact><Fact label="Befattning">{person.role || '—'}</Fact><Fact label="Startdatum">{formatDate(employment?.startDate)}</Fact><Fact label="Slutdatum">{formatDate(employment?.endDate)}</Fact><Fact label="Sysselsättningsgrad">{employment ? `${employment.percentage} %` : '—'}</Fact><Fact label="Veckoarbetstid">{employment ? `${employment.hoursPerWeek} timmar` : '—'}</Fact><Fact label="Anställningsnummer">{person.employeeNumber || '—'}</Fact></> : <div className="hr-empty"><LockKeyhole size={28} /><strong>Begränsad åtkomst</strong><p>Du saknar rättighet att läsa anställningsuppgifter.</p></div>}</Panel><Panel title="Lön & ersättning" icon={<LockKeyhole size={18} />} actions={cap('salaryWrite') && <button className="office-link" onClick={onSalaryEdit}><Pencil size={14} /> Redigera</button>}>{cap('salaryRead') ? <><Alert>Löneuppgifterna i demot är fiktiva. Löneutbetalning ingår inte.</Alert><Fact label="Löneform">{salary ? salary.kind === 'monthly' ? 'Månadslön' : 'Timlön' : 'Ej registrerad'}</Fact><Fact label="Belopp">{salary ? `${salary.amount.toLocaleString('sv-SE', { minimumFractionDigits: 2 })} kr${salary.kind === 'hourly' ? '/timme' : '/månad'}` : '—'}</Fact><Fact label="Gäller från">{formatDate(salary?.effectiveFrom)}</Fact><Fact label="Nästa lönerevision">{formatDate(salary?.nextReview)}</Fact>{salary?.note && <p>{salary.note}</p>}</> : <div className="hr-protected"><LockKeyhole size={32} /><h3>Löneuppgifter är skyddade</h3><p>Separat HR-behörighet krävs för att läsa eller ändra lön. Befattning och chefstitel ger ingen automatisk åtkomst.</p><Pill tone="grey">Begränsad åtkomst</Pill></div>}</Panel></div>;
}

function useSubmit(onSave: (event: FormEvent<HTMLFormElement>) => Promise<void>) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return { busy, error, submit: async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); try { await onSave(event); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Uppgifterna kunde inte sparas.'); } finally { setBusy(false); } } };
}
function FormFooter({ busy, onClose, label = 'Spara' }: { busy: boolean; onClose: () => void; label?: string }) { return <div className="hr-dialog-actions"><button type="button" className="office-btn outline" onClick={onClose} disabled={busy}>Avbryt</button><button className="office-btn" disabled={busy}>{busy ? 'Sparar…' : label}</button></div>; }
function PersonForm({ response, person, users, createLoginOnEdit = false, onClose, onSave, onCompany }: {
  response: PersonnelResponse; person?: Person; users: OfficeUser[]; createLoginOnEdit?: boolean;
  onClose: () => void; onCompany: () => void;
  onSave: (person: Partial<Person> & Pick<Person, 'name' | 'kind'>, clearFields?: Extract<PersonnelCommand, {action: 'person.save'}>['clearFields'], createAccount?: PersonAccountCreation) => Promise<void>;
}) {
  const [id] = useState(() => person?.id ?? `person_${crypto.randomUUID().replace(/-/g, '_')}`);
  const [kind, setKind] = useState<Person['kind']>(person?.kind ?? 'employee');
  const hasExternalAccount = response.data.externalAccounts.some(account => account.personId === person?.id);
  const mayManageStaff = response.capabilities.includes('users');
  const mayManageExternal = response.capabilities.includes('externalAccounts');
  const [staffUserId, setStaffUserId] = useState(person?.userId ?? '');
  const [createLogin, setCreateLogin] = useState(() => (!person || createLoginOnEdit) && (person?.kind === 'external' ? mayManageExternal && !hasExternalAccount : mayManageStaff && !person?.userId));
  const [canDrive, setCanDrive] = useState(person?.canDrive || createLoginOnEdit && person?.kind === 'external' || false);
  const [siteIds, setSiteIds] = useState<string[]>(person?.siteIds ?? (response.sites[0] ? [response.sites[0].id] : []));
  const canCreateLogin = kind === 'employee' ? mayManageStaff && !staffUserId : mayManageExternal && !hasExternalAccount;
  const { busy, error, submit } = useSubmit(async event => {
    const values = new FormData(event.currentTarget);
    if (!siteIds.length) throw new Error('Välj minst en anläggning.');
    const next: Partial<Person> & Pick<Person, 'name' | 'kind'> = {
      ...person, id, name: String(values.get('name')).trim(), kind, active: values.get('active') === 'on',
      role: String(values.get('role')).trim(), team: String(values.get('team')).trim(),
      phone: String(values.get('phone')).trim(), email: String(values.get('email')).trim(), address: String(values.get('address')).trim(),
      employeeNumber: kind === 'employee' ? String(values.get('employeeNumber')).trim() : undefined,
      managerId: String(values.get('managerId') || '') || undefined,
      companyId: kind === 'external' ? String(values.get('companyId') || '') || undefined : undefined,
      userId: kind === 'employee' ? (mayManageStaff ? staffUserId || undefined : person?.userId) : undefined,
      canDrive, siteIds, vehicleId: canDrive ? String(values.get('vehicleId') || '') || undefined : undefined,
    };
    const createAccount: PersonAccountCreation | undefined = createLogin && canCreateLogin
      ? kind === 'employee' ? { kind: 'staff' } : { kind: 'external', username: String(values.get('username') || '').trim(), password: String(values.get('password') || '') }
      : undefined;
    if (createAccount?.kind === 'external' && (!canDrive || !next.vehicleId)) throw new Error('Välj ett ordinarie fordon för chaufförsinloggningen.');
    const clearFields = (['managerId', 'companyId', 'userId', 'vehicleId'] as const).filter(key => Boolean(person?.[key]) && !next[key]);
    await onSave(next, clearFields, createAccount);
  });
  const changeKind = (nextKind: Person['kind']) => {
    setKind(nextKind); setStaffUserId('');
    setCreateLogin(nextKind === 'employee' ? mayManageStaff : mayManageExternal && !hasExternalAccount);
    if (nextKind === 'external') setCanDrive(true);
  };
  return <Dialog title={person ? 'Redigera person' : 'Lägg till person'} description="Personal, inloggning och förarprofil på samma personkort." onClose={onClose}>
    <form onSubmit={submit}><div className="hr-form-grid">
      <Field label="Namn *" full><input name="name" defaultValue={person?.name} required maxLength={150} /></Field>
      <Field label="Persontyp"><select aria-label="Persontyp" value={kind} disabled={Boolean(person?.userId || hasExternalAccount)} onChange={event => changeKind(event.target.value as Person['kind'])}><option value="employee">Anställd</option><option value="external">Extern chaufför</option></select></Field>
      <Field label="Befattning"><input name="role" defaultValue={person?.role} placeholder="T.ex. chaufför" /></Field>
      <Field label="Team"><input name="team" defaultValue={person?.team} list="hr-teams" /><datalist id="hr-teams">{Array.from(new Set(response.data.people.map(value => value.team).filter(Boolean))).map(team => <option key={team} value={team} />)}</datalist></Field>
      <Field label="Chef / gruppledare"><select name="managerId" defaultValue={person?.managerId ?? ''}><option value="">Ej vald</option>{response.data.people.filter(value => value.active && value.kind === 'employee' && value.id !== person?.id).map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></Field>
      <Field label="Telefon"><input name="phone" type="tel" defaultValue={person?.phone} /></Field><Field label="E-post"><input name="email" type="email" defaultValue={person?.email} /></Field>
      <Field label="Adress" full><input name="address" defaultValue={person?.address} /></Field>
      {kind === 'employee' ? <Field label="Anställningsnummer" full><input name="employeeNumber" defaultValue={person?.employeeNumber} /></Field> : <Field label="Åkeri *" full><select name="companyId" aria-label="Åkeri *" defaultValue={person?.companyId ?? ''} required><option value="">Välj åkeri</option>{response.data.companies.map(company => <option key={company.id} value={company.id}>{company.name}</option>)}</select><button type="button" className="office-link" onClick={onCompany}><Plus size={14} /> Lägg till åkeri</button></Field>}
      <div className="hr-field full"><span>Anläggningar *</span><div className="hr-checkbox-list">{response.sites.map(site => <label key={site.id}><input type="checkbox" checked={siteIds.includes(site.id)} onChange={event => setSiteIds(previous => event.target.checked ? [...previous, site.id] : previous.filter(value => value !== site.id))} />{site.name}</label>)}</div></div>
      <label className="hr-checkbox full"><input type="checkbox" checked={canDrive} onChange={event => setCanDrive(event.target.checked)} /> Kan bokas som förare</label>
      {canDrive && <Field label="Ordinarie fordon" full><select name="vehicleId" aria-label="Ordinarie fordon" defaultValue={person?.vehicleId ?? ''} required={kind === 'external' && createLogin && canCreateLogin}><option value="">Ej valt</option>{response.transport.vehicles.map(vehicle => <option key={vehicle.id} value={vehicle.id}>{vehicle.name} · {vehicle.registration}</option>)}</select></Field>}
      <label className="hr-checkbox full"><input name="active" type="checkbox" defaultChecked={person?.active ?? true} /> Aktiv person</label>
      {(kind === 'employee' ? mayManageStaff : mayManageExternal) && <fieldset className="hr-account-options full"><legend><KeyRound size={16} /> Inloggning & behörigheter</legend>
        {canCreateLogin && <label className="hr-checkbox"><input type="checkbox" checked={createLogin} onChange={event => { setCreateLogin(event.target.checked); if (event.target.checked && kind === 'external') setCanDrive(true); }} /> Skapa inloggning</label>}
        {kind === 'employee' ? <>
          {createLogin && canCreateLogin && <p className="hr-muted">Ett konto skapas med grundläggande åtkomst. Välj fler behörigheter på personkortet efter sparandet. Personal väljer sitt konto i demoinloggningen.</p>}
          <Field label="Befintligt användarkonto" full><select name="userId" aria-label="Befintligt användarkonto" value={staffUserId} onChange={event => { setStaffUserId(event.target.value); if (event.target.value) setCreateLogin(false); }}><option value="">{createLogin ? 'Skapa ett nytt konto' : 'Inget konto kopplat'}</option>{users.filter(account => !response.data.people.some(value => value.id !== person?.id && value.userId === account.id)).map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field>
          {staffUserId && <p className="hr-muted">Det befintliga kontot kopplas till personen. Ett nytt konto skapas inte.</p>}
        </> : hasExternalAccount ? <p className="hr-muted">Personen har redan en chaufförsinloggning. Lösenord och kontostatus hanteras på personkortets flik Inloggning & behörigheter.</p> : createLogin && <div className="hr-form-grid">
          <Field label="Användarnamn *"><input name="username" required autoComplete="off" pattern="[a-zA-Z0-9._-]+" minLength={3} maxLength={80} placeholder="T.ex. kalle.akeri" /></Field>
          <Field label="Lösenord *"><input name="password" type="password" aria-label="Lösenord *" required minLength={10} autoComplete="new-password" /><small>Minst 10 tecken.</small></Field>
          <p className="hr-muted full">Inloggning på /chauffor, med åtkomst till personens egna uppdrag hos det valda åkeriet.</p>
        </div>}
      </fieldset>}
    </div><Alert>Kompetenser och arbetstid avgör tillgänglighet. Lön och känsliga personaluppgifter har egna behörigheter.</Alert>{error && <Alert tone="red">{error}</Alert>}<FormFooter busy={busy} onClose={onClose} label="Spara person" /></form>
  </Dialog>;
}
function CompanyForm({ onClose, onSave }: { onClose: () => void; onSave: (company: {name: string; number: string; contact: string; phone: string; email: string}) => Promise<void> }) { const { busy, error, submit } = useSubmit(async event => { const values = new FormData(event.currentTarget); await onSave(Object.fromEntries(['name', 'number', 'contact', 'phone', 'email'].map(key => [key, String(values.get(key)).trim()])) as {name: string; number: string; contact: string; phone: string; email: string}); }); return <Dialog title="Lägg till åkeri" onClose={onClose}><form onSubmit={submit}><div className="hr-form-grid"><Field label="Företagsnamn *" full><input name="name" required /></Field><Field label="Organisationsnummer"><input name="number" /></Field><Field label="Kontaktperson"><input name="contact" /></Field><Field label="Telefon"><input name="phone" type="tel" /></Field><Field label="E-post"><input name="email" type="email" /></Field></div>{error && <Alert tone="red">{error}</Alert>}<FormFooter busy={busy} onClose={onClose} label="Spara åkeri" /></form></Dialog>; }
function EmploymentForm({ person, value, onClose, onSave }: { person: Person; value?: Employment; onClose: () => void; onSave: (employment: Employment) => Promise<void> }) { const { busy, error, submit } = useSubmit(async event => { const form = new FormData(event.currentTarget); await onSave({ personId: person.id, revision: value?.revision ?? 0, form: form.get('form') as Employment['form'], startDate: String(form.get('startDate')), endDate: String(form.get('endDate') || '') || undefined, percentage: Number(form.get('percentage')), hoursPerWeek: Number(form.get('hoursPerWeek')) }); }); return <Dialog title="Redigera anställning" description={person.name} onClose={onClose}><form onSubmit={submit}><div className="hr-form-grid"><Field label="Anställningsform"><select name="form" defaultValue={value?.form ?? 'permanent'}>{Object.entries(employmentNames).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field><Field label="Startdatum *"><input name="startDate" type="date" required defaultValue={value?.startDate ?? localToday()} /></Field><Field label="Slutdatum"><input name="endDate" type="date" defaultValue={value?.endDate} /></Field><Field label="Sysselsättningsgrad (%)"><input name="percentage" type="number" min="0" max="100" step="0.1" required defaultValue={value?.percentage ?? 100} /></Field><Field label="Veckoarbetstid (timmar)"><input name="hoursPerWeek" type="number" min="0" max="80" step="0.1" required defaultValue={value?.hoursPerWeek ?? 40} /></Field></div>{error && <Alert tone="red">{error}</Alert>}<FormFooter busy={busy} onClose={onClose} label="Spara anställning" /></form></Dialog>; }
function SalaryForm({ person, value, onClose, onSave }: { person: Person; value?: Salary; onClose: () => void; onSave: (salary: Salary) => Promise<void> }) { const { busy, error, submit } = useSubmit(async event => { const form = new FormData(event.currentTarget); await onSave({ personId: person.id, revision: value?.revision ?? 0, kind: form.get('kind') as Salary['kind'], amount: Number(form.get('amount')), effectiveFrom: String(form.get('effectiveFrom')), nextReview: String(form.get('nextReview') || '') || undefined, note: String(form.get('note')).trim() }); }); return <Dialog title="Lön & ersättning" description={`${person.name} · Fiktiva demouppgifter`} onClose={onClose}><form onSubmit={submit}><div className="hr-form-grid"><Field label="Löneform"><select name="kind" defaultValue={value?.kind ?? 'monthly'}><option value="monthly">Månadslön</option><option value="hourly">Timlön</option></select></Field><Field label="Belopp (kr) *"><input name="amount" type="number" min="0" step="0.01" required defaultValue={value?.amount} /></Field><Field label="Gäller från *"><input name="effectiveFrom" type="date" required defaultValue={value?.effectiveFrom ?? localToday()} /></Field><Field label="Nästa lönerevision"><input name="nextReview" type="date" defaultValue={value?.nextReview} /></Field><Field label="Notering" full><textarea name="note" defaultValue={value?.note} maxLength={1000} /></Field></div><Alert>Löneutbetalning ingår inte i demot.</Alert>{error && <Alert tone="red">{error}</Alert>}<FormFooter busy={busy} onClose={onClose} label="Spara löneuppgifter" /></form></Dialog>; }
function CompetencyForm({ person, value, onClose, onSave }: { person: Person; value?: Competency; onClose: () => void; onSave: (competency: Omit<Competency, 'id' | 'revision'> & {id?: string; revision?: number}) => Promise<void> }) { const { busy, error, submit } = useSubmit(async event => { const form = new FormData(event.currentTarget); await onSave({ ...value, personId: person.id, type: form.get('type') as Competency['type'], name: String(form.get('name')).trim(), scope: String(form.get('scope')).trim(), codes: String(form.get('codes')).split(/[,;\s/]+/).filter(Boolean).map(code => form.get('type') === 'license' ? code.toUpperCase() : ['ykb', 'adr'].includes(String(form.get('type'))) ? code.toLowerCase() : code), validFrom: String(form.get('validFrom')), validTo: String(form.get('validTo') || '') || undefined, verified: form.get('verified') === 'on' }); }); return <Dialog title={value ? 'Redigera kompetens' : 'Lägg till kompetens'} description={person.name} onClose={onClose}><form onSubmit={submit}><div className="hr-form-grid"><Field label="Kompetenstyp"><select name="type" defaultValue={value?.type ?? 'license'}>{Object.entries(competencyNames).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field><Field label="Benämning *"><input name="name" defaultValue={value?.name} required placeholder="T.ex. Körkort C / CE" /></Field><Field label="Omfattning"><input name="scope" defaultValue={value?.scope} placeholder="T.ex. styckegods" /></Field><Field label="Behörighetskoder *"><input name="codes" required defaultValue={value?.codes.join(', ')} placeholder="T.ex. C, CE eller goods för YKB" /><small>Separera med komma. YKB: goods · ADR: packages.</small></Field><Field label="Giltig från *"><input name="validFrom" type="date" defaultValue={value?.validFrom ?? localToday()} required /></Field><Field label="Giltig till"><input name="validTo" type="date" defaultValue={value?.validTo} /></Field><label className="hr-checkbox full"><input name="verified" type="checkbox" defaultChecked={value?.verified ?? false} /> Kontrollerad av personal</label></div><Alert>Endast verifierade, giltiga kompetenser kan uppfylla obligatoriska uppdragskrav.</Alert>{error && <Alert tone="red">{error}</Alert>}<FormFooter busy={busy} onClose={onClose} label="Spara kompetens" /></form></Dialog>; }
function ExternalAccountForm({ person, response, onClose, onSave }: { person: Person; response: PersonnelResponse; onClose: () => void; onSave: (command: Extract<PersonnelCommand, {action: 'externalAccount.save'}>) => Promise<void> }) {
  const account = response.data.externalAccounts.find(value => value.personId === person.id);
  const [active, setActive] = useState(account?.active ?? true); const [saved, setSaved] = useState(false);
  const { busy, error, submit } = useSubmit(async event => { const element = event.currentTarget; const form = new FormData(element); const password = String(form.get('password') || ''); await onSave({ action: 'externalAccount.save', personId: person.id, username: String(form.get('username')).trim(), active, ...(password ? { password } : {}) }); setSaved(true); const input = element.querySelector<HTMLInputElement>('input[name="password"]'); if (input) input.value = ''; });
  return <Dialog title="Extern chaufför · användarkonto" description={`${person.name} · ${response.data.companies.find(value => value.id === person.companyId)?.name ?? 'Åkeri'}`} onClose={onClose}><form onSubmit={submit}><div className="hr-account-state"><ShieldCheck size={28} /><div><strong>{person.name}</strong><small>Extern förarinloggning</small></div><Pill tone={active ? 'green' : 'grey'}>{active ? 'Aktivt' : 'Avaktiverat'}</Pill></div><div className="hr-form-grid"><Field label="Användarnamn *" full><input name="username" required autoComplete="off" defaultValue={account?.username ?? person.name.toLocaleLowerCase('sv-SE').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9._-]+/g, '.').replace(/^[._-]+|[._-]+$/g, '')} pattern="[a-zA-Z0-9._-]+" minLength={3} maxLength={80} /></Field><Field label={account ? 'Nytt lösenord (lämna tomt för att behålla)' : 'Lösenord *'} full><input name="password" type="password" required={!account} minLength={10} autoComplete="new-password" /></Field><label className="hr-checkbox full"><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)} /> Konto aktivt</label></div><Alert>Inloggning på <strong>/chauffor</strong>. Kontot visar endast personens egna tilldelade uppdrag inom det kopplade åkeriet. Kontors-, kundregister- och HR-åtkomst ingår inte.</Alert>{account && <p className="hr-muted">Senast inloggad: {formatDate(account.lastLoginAt)}</p>}{error && <Alert tone="red">{error}</Alert>}{saved && <Alert tone="green">Kontot är sparat. Lösenordet visas inte igen.</Alert>}<FormFooter busy={busy} onClose={onClose} label="Spara konto" /></form></Dialog>;
}
